ML-01
izakian/flask-app pull request #1
Opened 2020-05-17 23:53 UTC by izakian

Hi there please take a look and fix bugs

2020-05-17 23:56 UTC, hesam20052000 requested changes
Overall is good but please do these changes first. Thanks

2020-05-17 23:57 UTC, hesam20052000 commented on app.py
> +import os
Remove this

2020-05-17 23:57 UTC, hesam20052000 commented on app.py
> -
Extra space

2020-05-17 23:58 UTC, izakian commented on app.py
> -
done

2020-05-18 00:02 UTC, hesam20052000 approved these changes
Thanks

2020-05-18 00:02 UTC, merged